spring:
  application:
    name: ms-teacher
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
server:
  port: 7878
  

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
