spring:
  application:
    name: ms-config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Muerir/ms-config_server
          default-label: "main"
server:
  port: 8887

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka
