spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  zipkin:
    base-url: http://localhost:9411/

server:
  port: ${SERVER_PORT:8181}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}
  instance:
    hostname: localhost
    prefer-ip-address: true
