spring:
  application:
    name: ms-discovery

server:
  port: ${SERVER_PORT:8763}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    lease-expiration-duration-in-seconds: 20
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 3000
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}
